[package]
name = "pancake-macro"
version = "0.0.1"
authors = ["Jimmy Ye <jiy162@ucsd.edu>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
syn = { version = "1.0", features = ["extra-traits" ] }
quote = "1.0"
